f = open(r'D:\AIWorks\kechengbiao\deploy\index.html', 'r', encoding='utf-8')
h = f.read()
f.close()
i = h.find('showToast("已导出课程表配置")')
j = h.find('function importData')
print("Between export and import:")
print(repr(h[i:j]))
print("---")
print("Length:", j-i)